- android/app/src/debug/gen/com/example/literature/Manifest.java
- android/app/src/debug/gen/com/example/literature/R.java
- ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- lib/main.dart
- lib/screens/creategame.dart
- lib/screens/createroom.dart
- lib/screens/homepage.dart
- lib/screens/joinroom.dart
> Homepage design for Literature

- .gitignore
- lib/screens/createroom.dart
- lib/screens/joinroom.dart
- lib/screens/startgame.dart
- lib/screens/waitingpage.dart
- lib/utils/game_communication.dart
- lib/utils/websocket.dart
- node_server/app.js
- node_server/bin/www
- node_server/package-lock.json
- node_server/package.json
- pubspec.lock
- pubspec.yaml
Need additional enhancements but not within the scope of this PR
Workflow:
CreateRoom --------------> WaitingPage  -----------> Admin Starts Game (after 6 players have joined)
JoinRoom --------------> WaitingPage  ---------> Admin Starts Game (after 6 players have joined)
> Allows people to create/join the game

- lib/screens/joinroom.dart
- lib/screens/waitingpage.dart
- node_server/app.js
> Only lobby creators can start a game, after 6 players have joined

- android/app/src/main/AndroidManifest.xml
- ios/Runner/Info.plist
Change the App Name in AndroidMainfest.xml and Info.plist.
> Change App Name

- ios/Flutter/Debug.xcconfig
- ios/Flutter/Release.xcconfig
- ios/Podfile
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcworkspace/contents.xcworkspacedata
- lib/Consatnt/constant.dart
- lib/components/appbar.dart
- lib/screens/creategame.dart
- lib/screens/createroom.dart
- lib/screens/homepage.dart
- lib/screens/joinroom.dart
- lib/utils/audio.dart
What has been covered by this PR:
- Add ios builds
- Remove unnecessary "Constants" folder
- Play music on the homepage itself
- Add mute functionality on the appBar component
> Enhancement in audio playing

- lib/screens/createroom.dart
- lib/screens/joinroom.dart
- lib/screens/waitingpage.dart
- lib/utils/audio.dart
- lib/utils/game_communication.dart
- lib/utils/websocket.dart
- node_server/src/app.ts
- node_server/src/models/Room.ts
Players who want to join should provide a specific roomId for the above purpose. Stuff will be more clear after #30.
> Allow people to create and join rooms now

- lib/models/player.dart
- lib/screens/createroom.dart
- lib/screens/joinroom.dart
- lib/screens/waitingpage.dart
- node_server/src/app.ts
- node_server/src/models/Room.ts
Check the name from the backend that matches the current user.
> Lobby leader feature

- node_server/src/models/Room.ts
Fixes #37 temporarily, however, we need to implement it in the future.
> Disable player ID for now

- lib/components/appbar.dart
- lib/screens/homepage.dart
- pubspec.lock
- pubspec.yaml
1. Bug Fixes in Audio Player
2. Add SharedPreferences to Store the value of the last state of Audio Player.
> Audio Bug Fixes

- ios/Podfile.lock
- lib/screens/waitingpage.dart
- node_server/src/app.ts
Fixes #41 and a few other bugs such as the "Play" button should appear on the side of the lobby leader's name only.
> Waiting page bug fixes

- node_server/src/app.ts
- node_server/src/models/Room.ts
Fixes #35
- Change the player model id to number instead of string
- increment the number on new player join
- Change lobbyLeader field from String to Player type﻿
> increment id for new player join

- node_server/src/util/helper.ts
Add corner case condition, which was skipping the last element﻿
> fix shuffle bug

- android/.project
- android/.settings/org.eclipse.buildship.core.prefs
- android/app/.classpath
- android/app/.project
- android/app/.settings/org.eclipse.buildship.core.prefs
> New android deps

- android/.project
- android/.settings/org.eclipse.buildship.core.prefs
- android/app/.classpath
- android/app/.project
- android/app/.settings/org.eclipse.buildship.core.prefs
- lib/screens/createroom.dart
- lib/screens/joinroom.dart
> Data parsing inside switch blocks

- lib/screens/creategame.dart
> Initiate socket communication on the landing page

- lib/screens/createroom.dart
- lib/screens/joinroom.dart
- lib/utils/loader.dart
Add Loading Screen after Socket emits in Creating Game and Joining Game
> Adds Loading Screen

- ios/Podfile.lock
- lib/components/card_deck.dart
- lib/screens/gamescreen.dart
This PR has a couple of tasks:
> A player can now switch view of cards

- lib/screens/gamescreen.dart
- lib/utils/websocket.dart
- node_server/src/app.ts
- This logic handles how we are gonna monitor turns in our game.
- Also handles the case where a user ends his turn earlier than a particular time.
> Logic to handle each player's moves

- lib/components/player_view.dart
- lib/utils/websocket.dart
> Fixes unique "Hero" tag

- lib/components/player_view.dart
- lib/screens/gamescreen.dart
Changes player's color to green when his turn arrives.
> color identifier for a player's turn

- README.md
- lib/screens/createroom.dart
- lib/screens/joinroom.dart
- lib/utils/websocket.dart
- node_server/src/app.ts
- node_server/src/models/Room.ts
- node_server/src/util/helper.ts
- node_server/src/util/secrets.ts
This PR solves server build, and adds instructions to connect to server through local tunnels.
> Resolve build bugs and instructions to connect to server(From mobile devices).

- lib/components/player_view.dart
- lib/screens/gamescreen.dart
- lib/screens/waitingpage.dart
- node_server/src/app.ts
> Initial attempt to solve turns logic

- ios/Runner.xcodeproj/project.pbxproj
- lib/components/player_view.dart
- lib/screens/gamescreen.dart
- node_server/src/app.ts
- pubspec.lock
A player can only ask a card when he has his turn
and only to his opponents. On asking for a card a panel
shows up to handle the event.
> Groom turns logic a bit more

- lib/components/custom_dialog.dart
- lib/components/player_view.dart
- lib/utils/card_previewer.dart
Dialog box to handle when a user asks for a card.
> ask for cards: dialog box

- lib/provider/playerlistprovider.dart
- lib/screens/waitingpage.dart
- lib/utils/websocket.dart
- pubspec.lock
Changed the layout of the waiting screen
Restricted the play button exclusively for the leader to access.
> Waitingpage enhancement

- lib/screens/createroom.dart
- lib/screens/joinroom.dart
- lib/utils/websocket.dart
- node_server/package-lock.json
- node_server/package.json
- node_server/src/app.ts
- node_server/src/models/Room.ts
> This PR uses 'shortID' to create roomIds of type string.

- lib/components/custom_dialog.dart
- lib/components/player_view.dart
- lib/screens/gamescreen.dart
- lib/utils/card_previewer.dart
- lib/utils/websocket.dart
- node_server/src/app.ts
This PR handles the following things:
- If you're being asked and you have the card, you'll give it to the person who asked and it gets removed from your hand of cards. The person who asked will continue to play his turn.
- If you're being asked and you do not have the card, the turn of the person who asks will end.
> handles event on asking of a card

- lib/components/custom_dialog.dart
- lib/components/player_view.dart
- lib/screens/gamescreen.dart
- lib/utils/functions.dart
> Player can ask a card if he has a card from the same set

- android/.settings/org.eclipse.buildship.core.prefs
- lib/screens/createroom.dart
- lib/screens/joinroom.dart
- lib/screens/waitingpage.dart
- lib/utils/websocket.dart
- node_server/src/app.ts
#110 #105 #97 #52 
- Lobby leader could remove any player in waiting page
- Socket bugs due to multiple registered listeners
- When lobby leader leaves the room it removes all players from waiting page and marks the room as completed(due to some constraints can't delete the room at that point)
> Remove player & socket bugs 

- lib/screens/gamescreen.dart
- lib/screens/waitingpage.dart
- lib/utils/websocket.dart
> bug fixes on gamescreen, turns logic refactor

- lib/components/arena.dart
- lib/components/player_view.dart
updates the player scores. Fixes #115
> arena score update

- lib/screens/creategame.dart
- lib/screens/gamescreen.dart
- lib/utils/websocket.dart
- node_server/src/app.ts
> clean ups, also delete room when a player disconnects

- android/app/build.gradle
- android/app/google-services.json
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/res/values/strings.xml
- android/build.gradle
- ios/Podfile
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/AppDelegate.swift
- ios/Runner/GoogleService-Info.plist
- ios/Runner/Info.plist
- lib/main.dart
- lib/models/player.dart
- lib/models/playerfirebase.dart
- lib/screens/homepage.dart
- lib/screens/splash.dart
- pubspec.lock
- pubspec.yaml
Tracks the firebase auth changes
> Firebase auth

- ios/Podfile.lock
- lib/components/card_deck.dart
- lib/components/player_view.dart
- lib/screens/gamescreen.dart
> refactor card deck

- Dockerfile
- docker-compose.yml
- node_server/src/app.ts
Initially aimed at solving #125
> dockerise literature

- ios/Podfile.lock
- lib/components/appbar.dart
- lib/components/card_deck.dart
- lib/models/player.dart
- lib/provider/playerlistprovider.dart
- lib/screens/creategame.dart
- lib/screens/gamescreen.dart
- lib/store/artifacts.dart
- lib/store/card-designs/prime.dart
- lib/store/rarity.dart
- lib/store/store.dart
- node_server/src/app.ts
- pubspec.lock
- pubspec.yaml
Will implement the store as a part of this PR
> Literature store
